name: Update Submodules

on:
  push:
    branches:
      - 'blogposts'

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main' # Specify the main branch

      - name: Set up Git
        run: |
          git config --global user.name "Automated Release"
          git config --global user.email "admin@kalitsune.net"

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge
          git add .
          git commit -m "ðŸ”„ Update submodules" || echo "No changes to commit"
          git push origin main
